name: "sign-push-action"
author: rmartsev
description: "Sign docker images and push to container registry"
branding:
  icon: "award"
  color: "green"
inputs:
  image-tags:
    description: "list of image tags"
    required: true
  image-digest:
    description: "image digest"
    required: true
  cosign-private-key:
    description: "cosign private key"
    required: true
  cosign-password:
    description: "cosign password for private key"
    required: true
  codign-installer-version:
    description: "sigstore/cosign-installer version"
    required: false
    default: "v3.5.0"

runs:
  using: "composite"

  steps:

  - name: Install Cosign
    uses: "sigstore/cosign-installer@${{ inputs.codign-installer-version }}"

  - name: Sign image with a key
    env:
      TAGS: ${{ inputs.image-tags }}
      COSIGN_PRIVATE_KEY: ${{ inputs.cosign-private-key }}
      COSIGN_PASSWORD: ${{ inputs.cosign-password }}
      DIGEST: ${{ inputs.image-digest }}
    run: |
      images=""
      for tag in ${TAGS}; do
        images+="${tag}@${DIGEST} "
      done
      cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
    shell: bash
